[package]
name = "supermarketcrawler"
version = "0.1.0"
authors = ["Daoud Clarke <daoud.clarke@gmail.com>"]

[dependencies]
reqwest = "0.2.0"
select = { git = "https://github.com/utkarshkukreti/select.rs" }
